print()
greeting = open('hello.txt','r')
print(greeting)
print()
print(greeting.read())
print()
greeting.close()
f= open('hello.txt', 'r')
print("file name: ", f.name)
print("file mode: ", f.mode)
contents = f.read()
print("contents: ", contents)
print("Is file closed? ",f.closed)
f.close()
print("IS file closed? ",f.closed)
print()
newFile = open('newfile.txt', 'w')
print(newFile)
newFile.write("This is a new file created using python.")
newFile.closed()
print()
fileOR = open('newFile.txt', 'w')
fileOR.write("The contents of the newFile is now changed.")
fileOR.closed()
print()
appendFile = open("hello.txt", 'a')
appendFile.write("\n\nDont forget to smile today :)")
appendFile.closed()

with open("hello.txt", 'r') as f:
    contents= f.read()
    print(contents)
print()    